export const CryptoVisionSaleABI = [
  { type: 'receive', stateMutability: 'payable' },
  { type: 'function', name: 'TOKENS_PER_ETH', inputs: [], outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'acceptOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'buyTokens', inputs: [], outputs: [], stateMutability: 'payable' },
  { type: 'function', name: 'endSale', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'owner', inputs: [], outputs: [{ name: '', type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'pendingOwner', inputs: [], outputs: [{ name: '', type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'renounceOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'saleActive', inputs: [], outputs: [{ name: '', type: 'bool' }], stateMutability: 'view' },
  { type: 'function', name: 'token', inputs: [], outputs: [{ name: '', type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'tokensRemaining', inputs: [], outputs: [{ name: 'remaining', type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'totalTokensSold', inputs: [], outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'transferOwnership', inputs: [{ name: 'newOwner', type: 'address' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'withdrawETH', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'event', name: 'ETHWithdrawn', inputs: [{ name: 'amount', type: 'uint256', indexed: false }], anonymous: false },
  { type: 'event', name: 'OwnershipTransferStarted', inputs: [{ name: 'previousOwner', type: 'address', indexed: true }, { name: 'newOwner', type: 'address', indexed: true }], anonymous: false },
  { type: 'event', name: 'OwnershipTransferred', inputs: [{ name: 'previousOwner', type: 'address', indexed: true }, { name: 'newOwner', type: 'address', indexed: true }], anonymous: false },
  { type: 'event', name: 'SaleEnded', inputs: [{ name: 'unsoldTokensReturned', type: 'uint256', indexed: false }, { name: 'ethWithdrawn', type: 'uint256', indexed: false }], anonymous: false },
  { type: 'event', name: 'TokensPurchased', inputs: [{ name: 'buyer', type: 'address', indexed: true }, { name: 'ethAmount', type: 'uint256', indexed: false }, { name: 'tokenAmount', type: 'uint256', indexed: false }], anonymous: false },
  { type: 'error', name: 'ETHTransferFailed', inputs: [] },
  { type: 'error', name: 'InsufficientTokenSupply', inputs: [] },
  { type: 'error', name: 'MustSendETH', inputs: [] },
  { type: 'error', name: 'NoETHToWithdraw', inputs: [] },
  { type: 'error', name: 'OwnableInvalidOwner', inputs: [{ name: 'owner', type: 'address' }] },
  { type: 'error', name: 'OwnableUnauthorizedAccount', inputs: [{ name: 'account', type: 'address' }] },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
  { type: 'error', name: 'SafeERC20FailedOperation', inputs: [{ name: 'token', type: 'address' }] },
  { type: 'error', name: 'SaleNotActive', inputs: [] },
] as const
